# Training configuration
batch_size: 32
max_epochs: 100
learning_rate: 1e-4
num_workers: 4
checkpoint_dir: "checkpoints"
log_dir: "logs"
patience: 10
gradient_clip_val: 1.0
val_check_interval: 1.0

# Ensemble settings
ensemble:
  enabled: true
  num_folds: 5
  combine_train_val: true  # Whether to combine train+val for k-fold CV