# Training configuration
batch_size: 32
num_workers: 4
learning_rate: 1e-4
max_epochs: 100
patience: 10
gradient_clip_val: 1.0
checkpoint_dir: "checkpoints"
log_dir: "logs"
val_check_interval: 0.25 # Validate every 25% of training epoch	

dataloader:
  prefetch_factor: 2
  persistent_workers: true
  pin_memory: true

# Ensemble settings
ensemble:
  enabled: true
  num_folds: 5
  combine_train_val: true  # Whether to combine train+val for k-fold CV